const CLAVE="reparto-panaderia-josue";
let datos=cargarDatos(),clienteOtrosActual="",otrosBorrador=[];
function uid(){return crypto&&crypto.randomUUID?crypto.randomUUID():"id-"+Date.now()+"-"+Math.random().toString(16).slice(2)}
function hoy(){return new Date().toISOString().slice(0,10)}
function n(v){return Number(v||0)}
function pesos(v){return new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(n(v))}
function esc(t){return String(t||"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function etiquetaFecha(f){let p=String(f).split("-");return p.length===3?`${p[2]}-${p[1]}`:f}
function inicial(){const base=[["Adolfina",2,4400,4400,20000],["Antonia",4,8600,8500,20000],["Maria",3,-200,0,15000],["Serafin",2,8800,4400,25000],["Clara",0,0,0,12000],["Mercedes",0,84000,0,50000],["Mirta picass",0,0,0,12000],["Naty",0,0,0,12000],["Romero",8,143000,0,60000]];let clientes=base.map((c,i)=>({id:uid(),nombre:c[0],direccion:"",horario:"",precioPan:"",precioFactura:"",limite:c[4],orden:i+1}));let f=hoy();return{usuarioActual:"",ingresos:[],precios:[{id:uid(),producto:"Pan",precio:2200,pesable:true},{id:uid(),producto:"Factura",precio:350,pesable:false},{id:uid(),producto:"Prepizza",precio:1000,pesable:false},{id:uid(),producto:"Pan rallado",precio:800,pesable:true}],pedidos:[],panParaRallar:[],clientes,fechaActual:f,dias:{[f]:clientes.map((c,i)=>({clienteId:c.id,kg:base[i][1],deudaAnterior:base[i][2],pago:base[i][3],mp:0,otros:0,factura:0,prepizza:0,rallado:i===0?4:0,panParaRallarKg:0,otrosProductos:[],observacion:"",horaPago:""}))}}}
function cargarDatos(){let d=localStorage.getItem(CLAVE);d=d?JSON.parse(d):inicial();normalizar(d);return d}
function guardarDatos(){localStorage.setItem(CLAVE,JSON.stringify(datos))}
function normalizar(d){d.pedidos=d.pedidos||[];d.panParaRallar=d.panParaRallar||[];d.precios=(d.precios||[]).map(p=>({...p,pesable:!!p.pesable}));d.clientes.forEach((c,i)=>{if(!c.orden)c.orden=i+1});Object.values(d.dias||{}).forEach(fs=>fs.forEach(f=>{f.deudaAnterior=n(f.deudaAnterior);f.panParaRallarKg=n(f.panParaRallarKg);f.observacion=typeof f.observacion==="string"?f.observacion:"";f.otrosProductos=Array.isArray(f.otrosProductos)?f.otrosProductos:(f.otros?[{productoId:"",nombre:"Otros",precio:n(f.otros),cantidad:1}]:[])}))}
function clientesOrdenados(){return [...datos.clientes].sort((a,b)=>n(a.orden)-n(b.orden))}
function fechasOrdenadas(){return Object.keys(datos.dias).sort()}
function precioGeneral(p){let x=datos.precios.find(a=>a.producto.toLowerCase()===p.toLowerCase());return n(x&&x.precio)}
function precioPan(c){return n(c.precioPan)||precioGeneral("Pan")}
function precioFactura(c){return n(c.precioFactura)||precioGeneral("Factura")}
function totalProductoOtro(p){if(p.pesable){if(n(p.totalFinal)>0)return n(p.totalFinal);return redondear50Abajo(n(p.kgFinal||p.cantidad)*n(p.precioKilo||p.precio))}return n(p.precio)*n(p.cantidad)}
function redondear50Abajo(v){return Math.floor(n(v)/50)*50}
function totalOtros(f){return (f.otrosProductos||[]).reduce((s,p)=>s+totalProductoOtro(p),0)}
function totalFila(f,c){return n(f.kg)*precioPan(c)+n(f.factura)*precioFactura(c)+n(f.prepizza)*precioGeneral("Prepizza")+n(f.rallado)*precioGeneral("Pan rallado")+totalOtros(f)}
function debeFila(f,c){return n(f.deudaAnterior)+totalFila(f,c)}
function cuentaFila(f,c){return debeFila(f,c)-n(f.pago)-n(f.mp)}
function filaPorCliente(fecha,id){return (datos.dias[fecha]||[]).find(f=>f.clienteId===id)}
function actualizarEnContraDeDiasSiguientes(){let fs=fechasOrdenadas();for(let i=1;i<fs.length;i++){let ant=fs[i-1],act=fs[i];clientesOrdenados().forEach(c=>{let fa=filaPorCliente(ant,c.id),fb=filaPorCliente(act,c.id);if(fa&&fb)fb.deudaAnterior=cuentaFila(fa,c)})}}
function filasDelDia(){datos.dias[datos.fechaActual]=datos.dias[datos.fechaActual]||[];clientesOrdenados().forEach(c=>{if(!datos.dias[datos.fechaActual].some(f=>f.clienteId===c.id))datos.dias[datos.fechaActual].push({clienteId:c.id,kg:0,deudaAnterior:0,pago:0,mp:0,otros:0,factura:0,prepizza:0,rallado:0,panParaRallarKg:0,otrosProductos:[],observacion:"",horaPago:""})});return datos.dias[datos.fechaActual]}
function mostrarSeccion(id){document.querySelectorAll(".seccion").forEach(s=>s.classList.remove("activa"));let e=document.getElementById(id);if(e)e.classList.add("activa")}
function elegirUsuario(nombre){let a=new Date();datos.usuarioActual=nombre;datos.ingresos.unshift({usuario:nombre,fecha:a.toLocaleDateString("es-AR"),hora:a.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})});guardarDatos();actualizarUsuario();renderIngresos();alert("Usuario elegido: "+nombre)}
function actualizarUsuario(){let t=document.getElementById("usuarioActual");if(t)t.textContent=datos.usuarioActual?"Usuario: "+datos.usuarioActual:"Usuario sin seleccionar";let r=document.getElementById("linkReportes");if(r)r.classList.toggle("oculto",datos.usuarioActual.toLowerCase()!=="josue");let b=document.getElementById("btnBorrarDia");if(b)b.classList.toggle("oculto",datos.usuarioActual.toLowerCase()!=="josue");renderPedidosInicio()}
function renderIngresos(){let tb=document.getElementById("tablaIngresos");if(!tb)return;tb.innerHTML=datos.ingresos.slice(0,20).map(i=>`<tr><td>${i.usuario}</td><td>${i.fecha}</td><td>${i.hora}</td></tr>`).join("")}
function renderPrecios(){let tb=document.getElementById("tablaPrecios");if(!tb)return;tb.innerHTML=datos.precios.map(p=>`<tr><td>${esc(p.producto)}</td><td>${pesos(p.precio)}</td><td>${p.pesable?"Pesable":"Unidad"}</td><td><button onclick="editarPrecio('${p.id}')">Editar</button></td></tr>`).join("")}
function editarPrecio(id){let p=datos.precios.find(x=>x.id===id);precioId.value=p.id;productoNombre.value=p.producto;productoPrecio.value=p.precio;productoPesable.checked=!!p.pesable}
function guardarPrecio(e){e.preventDefault();let id=precioId.value,p={id:id||uid(),producto:productoNombre.value.trim(),precio:n(productoPrecio.value),pesable:productoPesable.checked};datos.precios=id?datos.precios.map(x=>x.id===id?p:x):[...datos.precios,p];e.target.reset();precioId.value="";guardarDatos();renderPrecios()}
function renderClientes(){let tb=document.getElementById("tablaClientes");if(!tb)return;tb.innerHTML=clientesOrdenados().map(c=>`<tr><td>${esc(c.nombre)}</td><td>${esc(c.direccion)||"-"}</td><td>${esc(c.horario)||"-"}</td><td>${c.precioPan?pesos(c.precioPan):"General"}</td><td>${c.precioFactura?pesos(c.precioFactura):"General"}</td><td>${pesos(c.limite)}</td><td>${c.orden}</td><td><button onclick="editarCliente('${c.id}')">Editar</button> ${c.direccion?`<a class="mapa" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.direccion)}">Maps</a>`:""}</td></tr>`).join("")}
function editarCliente(id){let c=datos.clientes.find(x=>x.id===id);clienteId.value=c.id;clienteNombre.value=c.nombre;clienteDireccion.value=c.direccion;clienteHorario.value=c.horario;clientePrecioPan.value=c.precioPan;clientePrecioFactura.value=c.precioFactura;clienteLimite.value=c.limite;clienteOrden.value=c.orden}
function guardarCliente(e){e.preventDefault();let id=clienteId.value,c={id:id||uid(),nombre:clienteNombre.value.trim(),direccion:clienteDireccion.value.trim(),horario:clienteHorario.value.trim(),precioPan:clientePrecioPan.value,precioFactura:clientePrecioFactura.value,limite:n(clienteLimite.value),orden:n(clienteOrden.value)||datos.clientes.length+1};datos.clientes=id?datos.clientes.map(x=>x.id===id?c:x):[...datos.clientes,c];e.target.reset();clienteId.value="";filasDelDia();guardarDatos();renderClientes()}
function renderReparto(){let tb=document.getElementById("tablaReparto");if(!tb)return;actualizarEnContraDeDiasSiguientes();fechaReparto.value=datos.fechaActual;renderDiasTabs();let tv=0,te=0,tm=0,td=0;tb.innerHTML=filasDelDia().sort((a,b)=>n((datos.clientes.find(c=>c.id===a.clienteId)||{}).orden)-n((datos.clientes.find(c=>c.id===b.clienteId)||{}).orden)).map(f=>{let c=datos.clientes.find(x=>x.id===f.clienteId);if(!c)return"";let debe=debeFila(f,c),cuenta=cuentaFila(f,c),vendido=totalFila(f,c);tv+=vendido;te+=n(f.pago);tm+=n(f.mp);td+=cuenta;return`<tr class="${n(c.limite)>0&&cuenta>n(c.limite)?"fila-alerta":""}"><td class="nombre-cliente">${esc(c.nombre)}</td>${inputReparto(f.clienteId,"kg",f.kg,"0.1")}<td class="deuda">${pesos(debe)}</td>${inputReparto(f.clienteId,"pago",f.pago,"1")}${inputReparto(f.clienteId,"mp",f.mp,"1")}<td class="${cuenta<=0?"pagado":"deuda"}">${pesos(cuenta)}</td><td><button class="boton-otros" onclick="abrirOtros('${f.clienteId}')">${pesos(totalOtros(f))}</button></td>${inputReparto(f.clienteId,"factura",f.factura,"1")}${inputReparto(f.clienteId,"prepizza",f.prepizza,"1")}${inputReparto(f.clienteId,"rallado",f.rallado,"1")}${inputReparto(f.clienteId,"panParaRallarKg",f.panParaRallarKg,"0.1")}<td><input class="input-observacion" type="text" value="${esc(f.observacion)}" onchange="cambiarReparto('${f.clienteId}','observacion',this.value)"></td>${inputReparto(f.clienteId,"deudaAnterior",f.deudaAnterior,"1")}<td>${f.horaPago||"-"}</td><td>${c.direccion?`<a class="mapa" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.direccion)}">Maps</a>`:"-"}</td></tr>`}).join("");totalVendido.textContent=pesos(tv);totalEfectivo.textContent=pesos(te);totalMp.textContent=pesos(tm);totalDeuda.textContent=pesos(td);renderHistorialPedidosDia();renderPanParaRallarPendiente()}
function inputReparto(id,campo,valor,paso){let min=campo==="deudaAnterior"?"":'min="0"';return`<td><input type="number" ${min} step="${paso}" value="${valor||0}" onchange="cambiarReparto('${id}','${campo}',this.value)"></td>`}
function cambiarReparto(id,campo,valor){let f=filasDelDia().find(x=>x.clienteId===id);f[campo]=campo==="observacion"?valor:n(valor);if((campo==="pago"||campo==="mp")&&n(valor)>0)f.horaPago=new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"});if(campo==="panParaRallarKg")guardarPanParaRallar(id,n(valor));guardarDatos();renderReparto()}
function guardarPanParaRallar(id,kg){let e=datos.panParaRallar.find(x=>x.fechaRecibido===datos.fechaActual&&x.clienteId===id&&x.estado==="pendiente");if(kg<=0){if(e)e.estado="cancelado";return}if(e){e.kg=kg;return}datos.panParaRallar.push({id:uid(),clienteId:id,kg,fechaRecibido:datos.fechaActual,horaRecibido:new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"}),estado:"pendiente"})}
function pendientesPanParaRallar(){return datos.panParaRallar.filter(x=>x.estado==="pendiente")}
function renderDiasTabs(){let d=document.getElementById("diasTabs");if(!d)return;d.innerHTML=fechasOrdenadas().map(f=>`<button type="button" class="${f===datos.fechaActual?"activo":""}" onclick="cambiarDia('${f}')">${etiquetaFecha(f)}</button>`).join("")}
function cambiarDia(f){datos.fechaActual=f;filasDelDia();guardarDatos();renderReparto()}
function productosOtros(){let f=["pan","factura","prepizza","pan rallado"];return datos.precios.filter(p=>!f.includes(p.producto.toLowerCase()))}
function abrirOtros(id){let fila=filasDelDia().find(f=>f.clienteId===id),c=datos.clientes.find(x=>x.id===id);clienteOtrosActual=id;otrosBorrador=productosOtros().map(p=>{let carg=(fila.otrosProductos||[]).find(i=>i.productoId===p.id||i.nombre===p.producto);return{productoId:p.id,nombre:p.producto,precio:n(p.precio),pesable:!!p.pesable,cantidad:n(carg&&carg.cantidad)}});modalCliente.textContent=c?c.nombre:"";buscarOtro.value="";modalOtros.classList.remove("oculto");renderOtrosModal()}
function renderOtrosModal(){let bus=buscarOtro.value.trim().toLowerCase(),vis=otrosBorrador.filter(p=>p.nombre.toLowerCase().includes(bus));grillaOtros.innerHTML=vis.map(p=>{let i=otrosBorrador.indexOf(p);return`<button class="producto-card ${p.pesable?"pesable":""}" type="button" onclick="sumarOtro(${i})"><strong>${esc(p.nombre)}</strong><span>${pesos(p.precio)}${p.pesable?"/kg":""}</span><small>${p.pesable?"Pesable":"Unidad"}</small></button>`}).join("")||'<p class="vacio">Agrega productos en Configuracion.</p>';let sel=otrosBorrador.filter(p=>n(p.cantidad)>0);listaOtrosVenta.innerHTML=sel.map(p=>{let i=otrosBorrador.indexOf(p);return`<div class="linea-venta"><span>${esc(p.nombre)}</span><input type="number" min="0" step="${p.pesable?"0.001":"1"}" value="${p.cantidad}" onchange="cambiarCantidadOtro(${i},this.value)"><strong>${p.pesable?"A confirmar":pesos(totalProductoOtro(p))}</strong></div>`}).join("")||'<p class="vacio">Todavia no agregaste productos.</p>';totalOtrosModal.textContent=pesos(otrosBorrador.reduce((s,p)=>s+(p.pesable?0:totalProductoOtro(p)),0))}
function sumarOtro(i){otrosBorrador[i].cantidad=n(otrosBorrador[i].cantidad)+1;renderOtrosModal()}
function cambiarCantidadOtro(i,v){otrosBorrador[i].cantidad=n(v);renderOtrosModal()}
function confirmarOtros(){let fila=filasDelDia().find(f=>f.clienteId===clienteOtrosActual),prods=otrosBorrador.filter(p=>n(p.cantidad)>0);if(datos.usuarioActual.toLowerCase()==="josue")crearPedidoPendiente(clienteOtrosActual,prods);else fila.otrosProductos=prods;cerrarOtros();guardarDatos();renderReparto()}
function crearPedidoPendiente(id,productos){if(!productos.length)return;datos.pedidos.push({id:uid(),fecha:datos.fechaActual,clienteId:id,productos,estado:"pendiente",creadoPor:datos.usuarioActual,creadoHora:new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})});alert("Pedido guardado para confirmar en el inicio.")}
function pedidosPendientes(){return datos.pedidos.filter(p=>p.estado==="pendiente")}
function renderPedidosInicio(){let bloque=document.getElementById("pedidosInicio"),lista=document.getElementById("listaPedidos");if(!bloque||!lista)return;let pend=pedidosPendientes(),conf=pedidosConfirmados();bloque.classList.toggle("oculto",pend.length===0&&conf.length===0);lista.innerHTML=pend.map(p=>{let c=datos.clientes.find(x=>x.id===p.clienteId),items=p.productos.map((producto,indice)=>({producto,indice})).filter(i=>!i.producto.estado||i.producto.estado==="pendiente");if(!items.length)return"";return`<article class="pedido-card"><div><strong>${c?esc(c.nombre):"Cliente"}</strong><span>${etiquetaFecha(p.fecha)} - ${p.creadoHora||""}</span></div><div class="pedido-productos">${items.map(i=>renderProductoPendiente(p.id,i.producto,i.indice)).join("")}</div></article>`}).join("");renderComprobantes()}
function renderProductoPendiente(pid,p,i){if(p.pesable)return`<div class="producto-pendiente"><strong>${esc(p.nombre)} x ${p.cantidad} kg aprox.</strong><input type="number" min="0" step="0.001" value="${p.kgFinal||p.cantidad||""}" placeholder="Kg final" oninput="cambiarDatoProductoPedido('${pid}',${i},'kgFinal',this.value)"><input type="number" min="0" step="1" value="${p.precioKilo||p.precio||""}" placeholder="Precio x kg" oninput="cambiarDatoProductoPedido('${pid}',${i},'precioKilo',this.value)"><span>${pesos(totalProductoOtro(p))}</span><button type="button" class="ok" onclick="confirmarProductoPedido('${pid}',${i})">OK</button><button type="button" class="no" onclick="rechazarProductoPedido('${pid}',${i})">X</button></div>`;return`<div class="producto-pendiente"><strong>${esc(p.nombre)} x ${p.cantidad}</strong><span></span><span></span><span>${pesos(totalProductoOtro(p))}</span><button type="button" class="ok" onclick="confirmarProductoPedido('${pid}',${i})">OK</button><button type="button" class="no" onclick="rechazarProductoPedido('${pid}',${i})">X</button></div>`}
function cambiarDatoProductoPedido(pid,i,campo,v){let p=datos.pedidos.find(x=>x.id===pid);if(!p)return;p.productos[i][campo]=n(v);if(p.productos[i].pesable)p.productos[i].totalFinal=totalProductoOtro(p.productos[i]);guardarDatos();renderPedidosInicio()}
function confirmarProductoPedido(pid,i){let p=datos.pedidos.find(x=>x.id===pid);if(!p)return;let prod=p.productos[i];if(prod.pesable){prod.kgFinal=n(prod.kgFinal||prod.cantidad);prod.precioKilo=n(prod.precioKilo||prod.precio);prod.totalFinal=totalProductoOtro(prod)}if(prod.pesable&&(n(prod.kgFinal)<=0||n(prod.precioKilo)<=0)){alert("Los productos pesables necesitan kg final y precio por kg.");return}let ant=datos.fechaActual;datos.fechaActual=p.fecha;let fila=filasDelDia().find(f=>f.clienteId===p.clienteId);prod.estado="confirmado";prod.confirmadoHora=new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"});fila.otrosProductos=[...(fila.otrosProductos||[]),prod];datos.fechaActual=ant;cerrarPedido(p);guardarDatos();renderPedidosInicio()}
function rechazarProductoPedido(pid,i){let p=datos.pedidos.find(x=>x.id===pid);if(!p)return;p.productos[i].estado="rechazado";cerrarPedido(p);guardarDatos();renderPedidosInicio()}
function cerrarPedido(p){if(!p.productos.some(x=>!x.estado||x.estado==="pendiente"))p.estado="cerrado"}
function pedidosConfirmados(){return datos.pedidos.filter(p=>p.productos.some(x=>x.estado==="confirmado"))}
function pedidosConResultado(){return datos.pedidos.filter(p=>p.productos.some(x=>x.estado==="confirmado"||x.estado==="rechazado"))}
function agruparPedidosPorCliente(ps){let m=new Map();ps.forEach(p=>{let c=datos.clientes.find(x=>x.id===p.clienteId),k=`${p.fecha}-${p.clienteId}`;if(!m.has(k))m.set(k,{fecha:p.fecha,cliente:c?c.nombre:"Cliente",productos:[]});p.productos.filter(x=>x.estado==="confirmado"||x.estado==="rechazado").forEach(x=>m.get(k).productos.push(x))});return[...m.values()]}
function textoComprobanteResultado(g){let l=[`Pedido ${g.cliente} - ${etiquetaFecha(g.fecha)}`],tot=0;g.productos.forEach(p=>{if(p.estado==="rechazado"){l.push(`${p.nombre}: no entregado`);return}let sub=totalProductoOtro(p);tot+=sub;l.push(p.pesable?`${p.nombre}: ${n(p.kgFinal).toLocaleString("es-AR")} kg x ${pesos(p.precioKilo)} = ${pesos(sub)}`:`${p.nombre} x ${p.cantidad} = ${pesos(sub)}`)});l.push(`Total: ${pesos(tot)}`);return l.join("\n")}
function renderHistorialPedidosDia(){let c=document.getElementById("historialPedidosDia");if(!c)return;let ps=pedidosConResultado().filter(p=>p.fecha===datos.fechaActual);if(!ps.length){c.innerHTML="";return}c.innerHTML=`<h3>Comprobantes del dia</h3>`+agruparPedidosPorCliente(ps).map((g,i)=>`<article class="comprobante-card"><div><strong>${esc(g.cliente)} - ${etiquetaFecha(g.fecha)}</strong><pre id="comprobanteDia${i}">${esc(textoComprobanteResultado(g))}</pre></div><button type="button" onclick="copiarTextoElemento('comprobanteDia${i}')">Copiar</button></article>`).join("")}
function renderPanParaRallarPendiente(){let c=document.getElementById("panRallarPendiente");if(!c)return;let ps=pendientesPanParaRallar();if(!ps.length){c.innerHTML="";return}c.innerHTML=`<h3>Pan para rallar pendiente</h3>`+ps.map(p=>{let cl=datos.clientes.find(x=>x.id===p.clienteId);return`<article class="pendiente-rallar"><div><strong>${cl?esc(cl.nombre):"Cliente"}</strong><span>${n(p.kg).toLocaleString("es-AR")} kg recibidos el ${etiquetaFecha(p.fechaRecibido)} ${p.horaRecibido||""}</span></div><button type="button" onclick="marcarPanRalladoDevuelto('${p.id}')">Devuelto</button></article>`}).join("")}
function marcarPanRalladoDevuelto(id){let x=datos.panParaRallar.find(p=>p.id===id);if(!x)return;x.estado="devuelto";x.fechaDevuelto=datos.fechaActual;x.horaDevuelto=new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"});guardarDatos();renderReparto()}
function renderComprobantes(){let c=document.getElementById("comprobantesPedidos");if(!c)return;c.innerHTML=agruparPedidosPorCliente(pedidosConResultado()).map((g,i)=>`<article class="comprobante-card"><div><strong>Comprobante ${esc(g.cliente)} - ${etiquetaFecha(g.fecha)}</strong><pre id="comprobante${i}">${esc(textoComprobanteResultado(g))}</pre></div><button type="button" onclick="copiarComprobante(${i})">Copiar</button></article>`).join("")}
function copiarComprobante(i){copiarTextoElemento(`comprobante${i}`)}
function copiarTextoElemento(id){let t=document.getElementById(id).textContent;if(navigator.clipboard){navigator.clipboard.writeText(t).then(()=>alert("Comprobante copiado."));return}let a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove();alert("Comprobante copiado.")}
function cerrarOtros(){modalOtros.classList.add("oculto");clienteOtrosActual="";otrosBorrador=[]}
function cambiarFechaReparto(){datos.fechaActual=fechaReparto.value||hoy();filasDelDia();guardarDatos();renderReparto()}
function nuevoDia(){let p=new Date(datos.fechaActual+"T12:00:00");p.setDate(p.getDate()+1);let nf=p.toISOString().slice(0,10),ant=filasDelDia();datos.dias[nf]=clientesOrdenados().map(c=>{let a=ant.find(f=>f.clienteId===c.id),deuda=a?cuentaFila(a,c):0;return{clienteId:c.id,kg:n(a&&a.kg),deudaAnterior:deuda,pago:0,mp:0,otros:0,factura:0,prepizza:0,rallado:0,panParaRallarKg:0,otrosProductos:[],observacion:"",horaPago:""}});datos.fechaActual=nf;guardarDatos();renderReparto()}
function borrarDiaActual(){if(datos.usuarioActual.toLowerCase()!=="josue"){alert("Solo Josue puede borrar dias.");return}let f=datos.fechaActual;if(!confirm("Seguro que queres borrar el dia "+etiquetaFecha(f)+"?"))return;delete datos.dias[f];let fs=fechasOrdenadas();if(!fs.length){datos.fechaActual=hoy();datos.dias[datos.fechaActual]=[];filasDelDia()}else datos.fechaActual=fs[fs.length-1];actualizarEnContraDeDiasSiguientes();guardarDatos();renderReparto()}
function renderReportes(){let sin=document.getElementById("bloqueSinPermiso"),rep=document.getElementById("bloqueReportes");if(!rep)return;let ok=datos.usuarioActual.toLowerCase()==="josue";sin.classList.toggle("oculto",ok);rep.classList.toggle("oculto",!ok);if(!ok)return;let res=fechasOrdenadas().map(fecha=>{let total=0,efectivo=0,mp=0;datos.dias[fecha].forEach(f=>{let c=datos.clientes.find(x=>x.id===f.clienteId);if(c){total+=totalFila(f,c);efectivo+=n(f.pago);mp+=n(f.mp)}});return{fecha,total,efectivo,mp}});dibujarGrafico("graficoTotal",res.map(r=>r.fecha),res.map(r=>r.total),"#2266d3");dibujarGrafico("graficoEfectivo",res.map(r=>r.fecha),res.map(r=>r.efectivo),"#17825d");dibujarGrafico("graficoMp",res.map(r=>r.fecha),res.map(r=>r.mp),"#8a45c7");renderRankings()}
function renderRankings(){let kilos=new Map(),deudas=new Map();Object.values(datos.dias).forEach(fs=>fs.forEach(f=>{let c=datos.clientes.find(x=>x.id===f.clienteId);if(c){kilos.set(c.nombre,n(kilos.get(c.nombre))+n(f.kg));deudas.set(c.nombre,cuentaFila(f,c))}}));topKilos.innerHTML=[...kilos.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([x,k])=>`<li>${esc(x)}: ${k.toLocaleString("es-AR")} kg</li>`).join("");topDeudas.innerHTML=[...deudas.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([x,d])=>`<li>${esc(x)}: ${pesos(d)}</li>`).join("")}
function dibujarGrafico(id,labels,vals,color){let cv=document.getElementById(id);if(!cv)return;let ctx=cv.getContext("2d"),m=38,w=cv.width-m*2,h=cv.height-m*2,max=Math.max(...vals,1);ctx.clearRect(0,0,cv.width,cv.height);ctx.strokeStyle="#cbd6e6";ctx.beginPath();ctx.moveTo(m,m);ctx.lineTo(m,cv.height-m);ctx.lineTo(cv.width-m,cv.height-m);ctx.stroke();let sp=w/Math.max(vals.length,1),bw=Math.max(22,sp-14);vals.forEach((v,i)=>{let bh=v/max*h,x=m+i*sp+6,y=cv.height-m-bh;ctx.fillStyle=color;ctx.fillRect(x,y,bw,bh);ctx.fillStyle="#172034";ctx.font="14px Segoe UI";ctx.fillText(pesos(v),x,Math.max(18,y-8));ctx.fillStyle="#60708a";ctx.font="12px Segoe UI";ctx.fillText((labels[i]||"").slice(5),x,cv.height-14)})}
function iniciar(){actualizarUsuario();renderIngresos();renderPrecios();renderClientes();renderReparto();renderReportes();let fp=document.getElementById("formPrecio");if(fp)fp.addEventListener("submit",guardarPrecio);let fc=document.getElementById("formCliente");if(fc)fc.addEventListener("submit",guardarCliente);let fr=document.getElementById("fechaReparto");if(fr)fr.addEventListener("change",cambiarFechaReparto);let nd=document.getElementById("btnNuevoDia");if(nd)nd.addEventListener("click",nuevoDia);let bd=document.getElementById("btnBorrarDia");if(bd)bd.addEventListener("click",borrarDiaActual)}
iniciar();
